# Generated by Django 4.0.8 on 2022-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='tilte',
            new_name='title',
        ),
    ]
