# Generated by Django 4.1.2 on 2022-11-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='public',
        ),
    ]
